<a href="https://colab.research.google.com/github/HammadAliKhanweb3/sentimental-analysis/blob/main/sentimental_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("train.txt",sep=";",header=None,names=["text","emotion"])

In [6]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [7]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [8]:
unique_emotions = df["emotion"].unique()
emotion_numbers = {}

i=0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i+=1

df["emotion"] = df["emotion"].map(emotion_numbers)
print(repr(df.loc[1, 'text']))

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [9]:



df['text'] = df['text'].apply(lambda x : x.lower())

df.loc[15]['text']

'i do not feel reassured anxiety is on each side'

In [10]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [11]:
df['text'] = df['text'].apply(remove_punc)
df.loc[15]['text']

'i do not feel reassured anxiety is on each side'

In [12]:

def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [13]:
df.loc[15]['text']

'i do not feel reassured anxiety is on each side'

In [14]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [15]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [16]:
import spacy

nlp = spacy.load("en_core_web_sm")

def remove_stop(txt):
  text = nlp(txt)
  cleaned = []
  for token in text:
    if not token.is_stop:
      cleaned.append(token.text)
  return ' '.join(cleaned)

df["text"] = df['text'].apply(remove_stop)

In [17]:
df.loc[1]['text']

'feeling hopeless damned hopeful cares awake'

In [18]:
df.head()

                                          text  emotion
0                           nt feel humiliated        0
1  feeling hopeless damned hopeful cares awake        0
2     m grabbing minute post feel greedy wrong        1
3    feeling nostalgic fireplace know property        2
4                              feeling grouchy        1

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( df["text"], df["emotion"], test_size=0.20, random_state=42)

In [42]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()

X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow  = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow,y_train)

pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test,pred_bow))

0.775

In [54]:

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

pred_tfidf = nb_model.predict(X_test_tfidf)
print(accuracy_score(y_test,pred_tfidf))

0.7315625

In [57]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression()

logistic_model.fit(X_train_tfid,y_train)

pred_log = logistic_model.predict(X_test_tfidf)
print(accuracy_score(y_test,pred_log))

0.865625